title: Vignesh V
logo: /assets/img/logo.png
description: I'm a data nerd with a passion of obtaining keener insights with the help of Machine Learning and Artificial Intelligence
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
